### PR TITLE
Use #pragma naked when available

### PR DESCRIPTION
**Pull request by AGraber**
Pawn compiler version check to use #pragma naked when available

### CODE REVIEW

**Comment by Y-Less** [comment]
Have you tested calling the functions returning arrays with this modification?

**Comment by Zeex** [comment]
Sorry, I can't merge this because the old returns already work well with all compilers, and the new version adds more clutter than improvement. 

Since `#pragma naked` simply disables the warning the only advantage I can see that there would be no extra `retn` opcode (and maybe a load). I'd like to keep things simple here. The whole repo is more like an example implementation for certain things than an actual library (although many use it as a library).

**Comment by Y-Less** [comment]
> The whole repo is more like an example implementation for certain things than an actual library

Wait, what?

**Comment by Zeex** [comment]
OK, maybe not "the whole repo", but many parts were initially created as just examples of what can be achieved with `#emit`. Perhaps over time it grew into something resembling a library., I don't know. Or maybe I have an amnesia, it was a while since I worked on this.

**Pull request closed without merging**
